# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=b'')),
                ('file2', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('ufm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmain.UploadFileModel')),
            ],
        ),
    ]
